apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viewers
  namespace: roles
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]
 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysa
  namespace: roles
 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: viewers-binding
  namespace: roles
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: viewers
subjects:
- kind: ServiceAccount
  name: mysa
  namespace: roles
 
---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: roles
spec:
  containers:
  - image: busybox
    name: test
    args:
    - sleep
    - "3600"
  serviceAccountName: mysa
