apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: task3
  name: task3
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: task2
    resources: {}
  - name: redis
    image: redis
  - name: nginx
    image: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
