apiVersion: v1
kind: Pod
metadata:
  name: task4
spec:
  containers:
  - name: second
    image: busybox
    command:
    - sleep
    - "10000"
  initContainers:
  - name: install
    image: busybox:1.28
    command:
    - touch
    - "/data/runfile.txt"
    volumeMounts:
    - name: workdir
      mountPath: "/data"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
