apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: task2
  name: task2
  namespace: mynamespace
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: alpine
    name: task2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
